data:
  batch_size: 8
  shuffle: true
  num_epochs: 3000
  validate_every: 100
lstm:
  input_size: 1
  hidden_size: 50
  num_layers: 1
  batch_first: true
  output_size: 1
experiment:
  name: "mlops_course"